"""Added creator name variable

Revision ID: 6c9e6939e91f
Revises: 3a5274455719
Create Date: 2025-05-03 00:36:51.686925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9e6939e91f'
down_revision: Union[str, None] = '3a5274455719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('creator_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'creator_name')
    # ### end Alembic commands ###
