"""Added query tag to vids

Revision ID: 77ac3df6e4f5
Revises: 7d7dcaabe715
Create Date: 2025-09-03 11:26:26.815804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ac3df6e4f5'
down_revision: Union[str, None] = '7d7dcaabe715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('q_tag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'q_tag')
    # ### end Alembic commands ###
