"""Added a var to user model

Revision ID: 7d7dcaabe715
Revises: 34f4f6d03c40
Create Date: 2025-06-06 14:05:17.649640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7dcaabe715'
down_revision: Union[str, None] = '34f4f6d03c40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('prof_img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'prof_img')
    # ### end Alembic commands ###
